apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server-deployment
  labels:
    app: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      volumes:
        - name: code-server-volume
          persistentVolumeClaim:
            claimName: code-server-volume-claim
      containers:
        - name: code-server
          image: code-server:latest
          resources:
            requests:
              cpu: 125m
              memory: 128M
            limits:
              cpu: 125m
              memory: 256M
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /home/coder/project
              name: code-server-volume
